---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit. In our example, we state that all our Jobs will use the same Docker
# container for building in.
shared:
  # Docker image to use as the desired build container. This typically takes the
  # form of "repo_name". Alternatively, you can define the image as
  # "repo_name:tag_label".
  #
  # (Source: https://hub.docker.com/r/library/buildpack-deps/)
  image: doximity/data_airflow:latest
  annotations:
    screwdriver.cd/buildPeriodically: H 0 * * *

# Job definition block
# "main" is a default job that all pipelines have
jobs:
  first_thing:
    requires: [~pr, ~commit]
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.foo "foobar"
  second_job:
    requires: first_thing
    steps:
      # The "make_target" step calls a Makefile target to perform some set of
      # actions. This is incredibly useful when you need to perform a multi-line
      # command.
      - make_target: make greetings
      # You can get metadata that was set using the command "meta get <key>".
      - get-metadata: meta get example
      # The "run_arbitrary_script" executes a script. This is an alternative to
      # a Makefile target where you want to run a series of commands related to
      # this step
      - run_arbitrary_script: ./my_script.sh
  parallel_job:
    requires: first_thing
    steps:
      - whatpips: pip list
      - say_something:  echo "Something"
