---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit. In our example, we state that all our Jobs will use the same Docker
# container for building in.
shared:
  image: ubuntu

# Job definition block
jobs:
  first_thing:
    annotations:
      screwdriver.cd/buildPeriodically: 5 * * * *
    #requires: [~pr, ~commit]
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.foo "foobar"
  second_job:
    requires: first_thing
    steps:
      - make_target: make greetings
      - get-metadata: meta get example
      - run_arbitrary_script: ./my_script.sh
  parallel_job:
    requires: first_thing
    steps:
      - whatpips: pip list
      - say_something:  echo "Something"
